Resources:
  IdLabelTimeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.activityTable}
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
        - AttributeName: secondaryKey
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
        - AttributeName: secondaryKey
          KeyType: HASH
      LocalSecondaryIndexes: 
        IndexName: secondaryKey
        KeySchema:
          - AttributeName: secondaryKey
            KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
