Resources:
  ActivityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.activityTable}
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
        - AttributeName: secondaryKey
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
        - AttributeName: secondaryKey
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: expiresAfter
        Enabled: true
